# Based on https://debezium.io/documentation/reference/1.2/tutorial.html#starting-mysql-database
version: '3.8'
services:
  zookeeper:
    image: debezium/zookeeper:1.2
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    networks:
      - debezium
  kafka:
    image: debezium/kafka:1.2
    environment:
      ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
    networks:
      - debezium
    depends_on:
      - zookeeper
  mysql:
    image: debezium/example-mysql:1.2
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
    ports:
      - "3306:3306"
    networks:
      - debezium
  connect:
    image: debezium/connect:1.2
    environment:
      BOOTSTRAP_SERVERS: "kafka:9092"
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
    ports:
      - "8083:8083"
    networks:
      - debezium
    depends_on:
      - zookeeper
      - kafka
      - mysql
networks:
  debezium: